name: GitHub Actions Update List
run-name: Updating list file 🚀
on:
  push:
  schedule:
    - cron: "46 2 * * *"
jobs:
  Update-List:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: nicotinoo/lavistica1970
          path: src
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install jinja2
          python update_list.py
      - uses: stefanzweifel/git-auto-commit-action@v4
